### ISSUE TITLE
If JavaScript also has to be used besides Ruby, Is it possible with Decaf?

### ISSUE THREAD

**Issue by raviagrwl420** [timimahoney/decaf#11]
I want to know how exactly Decaf integrates Ruby with WebKit. Is it possible to handle the DOM through both JavaScript and Ruby or you have to move completely to Ruby?

**Comment by timimahoney** [comment]
Decaf integrates Ruby at the same level as JavaScript. JavaScript is still there, so you can use both at the same time. Here's a little bit about [how Ruby is connected to the DOM](http://trydecaf.org/dom). It doesn't explain the whole inner workings, but it's a start.

**Comment by raviagrwl420** [comment]
The detection of JavaScript or Ruby is probably then done using the "type" attribute of the "script" tag.
@timahoney am I right?

**Comment by timimahoney** [comment]
Ah yeah. Sorry, I should write something more explicit about that. You can specify `type='text/ruby'` to specify that it's Ruby.
