### ISSUE TITLE
Add Ruby support in the main WebKit repository

### ISSUE THREAD

**Issue by KarateCowboy** [timimahoney/decaf#12]
I believe this should be in every browser going forward. Do you? If so, how may I help?

**Comment by timimahoney** [comment]
I do believe Ruby will be a useful tool in the browser, but it needs to be proven. The best thing to do now would be to make something that shows the benefits of Ruby as an alternative to JavaScript.

**Comment by KarateCowboy** [comment]
I am a Ruby developer, so I could potentially do something like that. I will clone your repository here and look at getting your creation running on Ubuntu linux. Maybe something along the lines of 'RQuery', or maybe Objects which let you do things like "canvas = HTML::Canvas.new({:some_att => 'some_val'})" would be nice.

Ruby's class system brings a lot of potential. Inheritance of other DOM objects and even the document itself allows for whole worlds and systems to be created. It might even be possible to create Ruby objects with built in handling for styles.  For example an HTML::Table::Row object with property 'background_color'. You could change the color value for red doing something like "my_tar.background_color.increase_red". Loop through that for a background that pulsates color changes. Just one idea.

I have a feeling that Ruby's fun nature will be naturally appealing to web developers for browser use, once they see some creative ideas put to code.

**Comment by timimahoney** [comment]
You're right, Ruby can be fun! Let me know what you come up with.

**Comment by timimahoney** [comment]
I'm going to close this for now to keep the issues section clean.
