### ISSUE TITLE
This project seems misguided

### ISSUE THREAD

**Issue by ghost** [timimahoney/decaf#3]
I think JavaScript and Ruby are being horribly misunderstood here...

**Comment by deoxxa** [comment]
+1

**Comment by kumavis** [comment]
@naomik  @deoxxa  haha wut??
If you want to make an argument as to why a repo should be abandoned, you're going to need to try/troll harder. I don't know, maybe provide a concrete reason? Unless of course you're taking a reverse approach and trying to brew up a storm around the issue and bring attention to the repo, in that case, good on you.
