### ISSUE TITLE
DOMClass#dup and related methods crash the app.

### ISSUE THREAD

**Issue by senthilnayagam** [timimahoney/decaf#5]
I was looking for programmatically open new window from console

$window.dup crashes the app every time

**Comment by senthilnayagam** [comment]
same behaviour with $window.clone as well

**Comment by timimahoney** [comment]
Ruby in the browser uses the same API as JavaScript, so the way to do it would be with [`window.open`](https://developer.mozilla.org/en-US/docs/DOM/window.open). However, that doesn't seem to work! I'll check it out.

That said, `dup` and `clone` shouldn't work for the DOM objects, but they shouldn't crash either. On DOM classes, `dup` and `clone` should either be undefined or redefined to something useful.

Thanks for the report!

**Comment by senthilnayagam** [comment]
Hi Tim, 

yeah I agree, you can redefine all those crash causing code for now, till you figure out a solution.

I have started adding my experience to wiki page, hope you dont mind, creating 2 pages to begin with "getting started" and "feature requests"

I want to know what standard library is included, that will help me choose a small project to explore all capabilities

another crash I could simulate was since bigint is not available if you try multiplying 2 large integers 1234567890*9876543210 the app would crash

Senthil

**Comment by timimahoney** [comment]
Thanks for the contributions to the Wiki! I'm going to keep it restricted to collaborators for now. You can make feature requests by making a new issue here and tagging it with the "feature" tag.

**Comment by timimahoney** [comment]
The `dup` and `clone` methods are now no longer available on WebKit objects. This is fixed on the 0.1.2 branch right now.
