### ISSUE TITLE
Run only one website like Fluid?

### ISSUE THREAD

**Issue by aemadrid** [timimahoney/decaf#6]
Gotta say I love this as it stands. If you could make this run only one site (no url bar) ala Fluid it would be great for my purposes.

**Comment by timimahoney** [comment]
It's definitely possible, and it's a cool idea, but I don't have any plans to do it at the moment. 

Right now, the build runs the MiniBrowser that is included with WebKit. You could modify that or build a Fluid-like app, then link the app against WebKit, WebCore, and JavaScriptCore from Decaf. Or, if Fluid uses the WebKit framework, then you could manually run Fluid with the Decaf frameworks. You would need to set the DYLD_FRAMEWORK_PATH environment variable.

However, I don't recommend this at the moment. The frameworks are unstable and insecure, and you may run into problems.

**Comment by aemadrid** [comment]
Cool, thanks for replying so soon.

## 

Adrian Madrid

aemadrid@gmail.com (mailto:aemadrid@gmail.com)
